#- alias: 'Nachtlicht ein'
#  trigger: 
#    platform: state
#    entity_id: sensor.zimmer_bewegung
#    to: 'True'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: group.all_lights
#        state: 'off'
#      - condition: numeric_state
#        entity_id: sensor.zimmer_helligkeit
#        below: '4000'
#  action:
#    service: light.turn_on
#    entity_id:
#      - light.bett
#    data:
#      brightness: 40
#      white_value: 255

- alias: 'Nachtlicht ein'
  trigger:
    platform: state
    entity_id: sensor.zimmer_bewegung
    to: 'True'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.zimmer_helligkeit
        below: '5000'
  action:
    service: light.turn_on
    entity_id:
      - light.bett
    data:
      brightness: 20
      white_value: 255

- alias: 'Nachtlicht aus'
  trigger:
    platform: state
    entity_id: sensor.zimmer_bewegung
    to: 'False'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.deckenlampe
        state: 'off'
      - condition: state
        entity_id: group.led_stripes
        state: 'off'
      - condition: state
        entity_id: group.schreibtisch_licht
        state: 'off'
      - condition: state
        entity_id: group.ambiente_licht
        state: 'off'
      - condition: state
        entity_id: automation.nachtlicht_ein
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bett

#- alias: 'Nachtlicht aus'
#  trigger:
#    platform: state
#    entity_id: sensor.zimmer_bewegung
#    to: 'False'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: automation.nachtlicht_ein
#        state: 'on'
#      - condition: state
#        entity_id: group.ambiente_light
#        state: 'off'
#      - condition: state
#        entity_id: group.deckenlampe
#        state: 'off'
#      - condition: state
#        entity_id: group.led_stripes
#        state: 'off'
#      - condition: state
#        entity_id: group.schreibtisch_light
#        state: 'off'
#  action:
#    - service: light.turn_on
#      entity_id:
#        - light.regal
#    - delay: 00:00:05
#    - condition: state
#      entity_id: sensor.zimmer_bewegung
#      state: 'False'
#    - service: light.turn_off
#      entity_id:
#        - light.bett

